### PR TITLE
feat: add Cluster::set_token_aware_routing_shuffle_replicas

### PR DESCRIPTION
**Pull request by jhgg**
self explanatory!

### CODE REVIEW

**Review by kw217 — APPROVED** [review]
LGTM! Not much to say on this one... :-)

**Comment by kw217** [comment]
Trivial conflict, and out-of-date. Best to just do one at a time. I'll try and check regularly during 0900-1700 UTC - is there any overlap with your hours?

**Comment by jhgg** [comment]
Should be good now.

**Comment by kw217** [comment]
Please pick just one to update - we have to do these one at a time, since each merge to master makes the remaining PRs out of date with it.

**Comment by jhgg** [comment]
> Please pick just one to update - we have to do these one at a time, since each merge to master makes the remaining PRs out of date with it.

Yeah :( Kinda struggling on this one - all 3 are ready for merge again - just pick whatever merges and I'll keep resolving. Surprised you can't click the update button yourself - must be because the branch is coming from my fork.

**Pull request merged**
