### PR TITLE
Adapt Session Arc and associate a Session to Statement, Prepared Statement & Batch

### PR DESCRIPTION
**Pull request by renancloudwalk**
Here are some **breaking** changes that might be included on v2.0.0 (This is a continuation of the work that began at #96 and #101, taking into account the commentaries over those two issues.)

Taken from @jhgg original PR:

```
This PR tries to improve upon that, by building that betterment directly into the library. This is most definitely a breaking change, but I think for the better. Given the ubiquity of async rust, I've also dropped support for the .wait() function on CassFuture, and some functions which used to return a CassFuture, now are just simple async fn's. If you are operating in a synchronous space, you can use something like https://docs.rs/futures/0.3.8/futures/executor/fn.block_on.html - which will provide the machinery required to execute the now async-only code.

Essentially, Session now implements Clone. The inner pointer to the cassandra session has been moved into a SessionInner, which is now wrapped in an Arc inside of Session.

From there, we can now Clone the given Session to the relevant Statement, PreparedStatement, and Batch (associated session resource). This provides a more safe API, as it makes it now impossible to use the wrong associated session resource with an incorrect session.
```

Remaining TODO list:
- [x] Create more tests calling `execute()` (I need to check the limitations of calling execute for the same statement multiple times)
- [x] Add more docs
- [x] Update the Changelog 
- [x] Add a migration guide

### CODE REVIEW

**Comment by renancloudwalk** [comment]
@kw217  to deal with the signing errors, I can squash those commits with a signature OR I can amend them, which path do you recommend? I'm a bit worried because half of the commits here don't belong to me, seems odd to sign them.

**Comment by kw217** [comment]
@jhgg are you happy with your commits being squashed?
@renancloudwalk can you confirm that all the squashed commits were signed before you squashed them?

Also - please let me know when this is ready to review so I can set aside time to go through it properly. Apologies if I have lower bandwidth than usual over the next two weeks.

**Comment by jhgg** [comment]
> @jhgg are you happy with your commits being squashed? @renancloudwalk can you confirm that all the squashed commits were signed before you squashed them?

I don't mind! Do with this code as you please!

**Comment by kw217** [comment]
Thanks @jhgg, I really appreciate the work you put in here. And thanks to @renancloudwalk for carrying it forward.

**Comment by renancloudwalk** [comment]
@kw217 I just added the changelog and the overall guidelines for users wanting to upgrade.

What do you say we proceed with the merge? Are there any other details? I can add more documentation on another PR (if you feel like it is needed)

**Comment by kw217** [comment]
Apologies for the delay. Thank you very much again for this - it looks great. I've made a few markups directly. I have a few more checks to do locally, and then I should be able to merge this.

**Review by kw217 — APPROVED** [review]
Thanks @renancloudwalk, this looks great. I've applied a few trivial markups and added a proper migration guide. I've also backed off from releasing 2.0.0 just yet - there is one other change that needs to be made first.

**Comment by kw217** [comment]
Published as 2.0.0. Enjoy.

**Comment by renancloudwalk** [comment]
Awesome!!!

**Pull request merged**
