### PR TITLE
change DATE type to u32

### PR DESCRIPTION
**Pull request by M5135213521asd3**
This will fix <error> message when debug/display cassandra DATE value.

### CODE REVIEW

**Comment by kw217** [comment]
Thanks @M5135213521asd3 for this very good spot - greatly appreciated! Oops!

Is the rest of the date handling OK? Cassandra has a slightly odd date type, 2^31 + number of days since the epoch.

Also it looks like there's a build failure - you need to sign your commit as described in CONTRIBUTING. Please can you fix that and force-push? Thanks!

**Comment by M5135213521asd3** [comment]
Rust (or cpp) driver itself return row value:  2^31 + days. 
I think this is fine, becuase it's described in cpp driver (maybe add some words in rust docu as well?) :

> The driver currently uses raw types to handle date and time because date and time handling is often very application specific in C/C++. It currently provides methods to handle converting Epoch (January 1, 1970) time in seconds to and from date/time.
> 
> **The date type uses an unsigned 32-bit integer (cass_uint32_t) to represent the number of days with Epoch centered at 2^31.** Because it’s centered at Epoch it can be used to represent days before Epoch. The time type uses a signed 64-bit integer (cass_int64_t) to represent the number of nanoseconds since midnight and valid values are in the range 0 to 86399999999999.

PS: Maybe if someone has some spare time, got_date() fn which will return i32 as a date from the epoch (-/+, before/after) will be helpfull. I joined rust comunity 3-4 weeks ago, and don't feel capable of doing it on the level...

**Review by M5135213521asd3 — COMMENTED** [review]
Signed-off-by: Marian Marencik <github@marianm.net>

**Review by kw217 — APPROVED** [review]
Thanks @M5135213521asd3 - this looks great to me!

**Comment by kw217** [comment]
Do you need a release urgently?

**Comment by M5135213521asd3** [comment]
@kw217 : Not needed for me...

**Comment by kw217** [comment]
Thanks. This will end up in the next release but I'll not kick that off immediately.

**Comment by M5135213521asd3** [comment]
Thank you.

**Pull request merged**
