### PR TITLE
future proof ci

### PR DESCRIPTION
**Pull request by rukai**
Same as https://github.com/Metaswitch/cassandra-sys-rs/pull/50
I also noticed we were missing `cargo fmt` on this repo so I copied that over.

### CODE REVIEW

**Comment by rukai** [comment]
Not sure whats up with the intermittent failure in test_rendering caused by `Value::get_str`, maybe its UB?
Will have to investigate another day.

**Comment by kw217** [comment]
Sigh, I haven't seen this error before - does look sadly like we might have exposed some UB by bumping the Ubuntu version. Thanks for investigating.

**Comment by rukai** [comment]
I've located the cause and raised an issue to track it here: https://github.com/Metaswitch/cassandra-rs/issues/153
I dont think I will be personally investigating #153 further any time soon though.

I've adjusted the test slightly to avoid the UB so that we can go ahead and land this PR.

**Comment by kw217** [comment]
Tweak looks fine for now - thanks. I'm happy that issue is independent of this PR.

**Review by kw217 — APPROVED** [review]
LGTM, thanks.

**Comment by kw217** [comment]
Hi @rukai - this seems to be waiting for a result from `build-and-test`, but there's no associated build that I can see. Looks like a bug in your `build.yml`. Can you take a look please?

**Comment by rukai** [comment]
Build-and-test is superceded by 4 new workflows, you will need to disable the check in branche protection for it. Then once this is merged enable the four new workflows in branch protection

**Pull request merged**
