### PR TITLE
date_from_epoch fn & decimal test for 0.000000000000 removed

### PR DESCRIPTION
**Pull request by M5135213521asd3**
Signed-off-by: Marian Marencik <github@marianm.net>

### CODE REVIEW

**Comment by M5135213521asd3** [comment]
cass_date_from_epoch - this is "good to have", it convert unix timestamp to cassandra "strange date" format. - we don't need to create own function for that

decimal test for 0.000000000000 removed - this is failing on:
```
---- test_decimal_round_trip stdout ----
thread 'test_decimal_round_trip' panicked at tests/basic.rs:347:13:
assertion `left == right` failed: Decimal test for literal CQL (zero with 16 trailing zero):  0.0000000000000000 and 0E-16
  **left: "0.0000000000000000"
 right: "0E-16"**
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I suppose it's because of some changes on DataStax C/C++ driver...

**Comment by kw217** [comment]
Re bigdecimal - we haven't seen evidence of this failing in CI: https://github.com/Metaswitch/cassandra-rs/actions/runs/8095417445/job/22122059443#step:10:79 passed quite recently, and it passes for me locally (with the 2.16 driver).

**Comment by kw217** [comment]
I stand by my comment that `cass_date_from_epoch` is too low-level. If you really need this you can get it from cassandra-sys directly; this library should provide a clean abstraction so should have a proper `Date` API.

**Comment by M5135213521asd3** [comment]
> Re bigdecimal - we haven't seen evidence of this failing in CI: https://github.com/Metaswitch/cassandra-rs/actions/runs/8095417445/job/22122059443#step:10:79 passed quite recently, and it passes for me locally (with the 2.16 driver).

Compared mine with this one, the diference was in bigdecimal version 0.4.2 vs 0.4.3, here from change report:

[https://github.com/akubera/bigdecimal-rs/releases](https://github.com/akubera/bigdecimal-rs/releases)
> Use exponential formatting (scientific-notation) if number of leading zeros is greater than 5
> so 1234e-304 is formatted as 1.234e-301 rather than 0.00.....{300-zeros)....00123

**Comment by kw217** [comment]
Ah, interesting. That's a breaking change so they're clearly not following semver. How about changing the test to `0.0000`? That should work in both versions.

**Comment by M5135213521asd3** [comment]
I will remove this pull and will create new just for bigdecimal

**Pull request closed without merging**
