### PR TITLE
chore: upgrade tokio to 1.0

### PR DESCRIPTION
**Pull request by jhgg**
#98 but correct.

### CODE REVIEW

**Comment by jhgg** [comment]
travisci seems to be fubar'd trying to pull from docker hub. will need to investigate this further.

**Review by kw217 — APPROVED** [review]
Apologies for closing the dependabot PR; this was *much* easier than I thought it was going to be. LGTM.

**Comment by jhgg** [comment]
Hmm. It still won't let me merge. Says I'm not authorized.

**Comment by kw217** [comment]
@jhgg can you try again now? `master` is a protected branch and I had to add you explicitly to the list of who can push.

**Pull request merged**
