### PR TITLE
feat: use parking_lot::Mutex

### PR DESCRIPTION
**Pull request by jhgg**
parking_lot::Mutex is faster than std::sync::Mutex, so let's use it for the critical lock in `CassFuture`.

This section of parking_lot's docs describes the difference: https://docs.rs/parking_lot/0.11.0/parking_lot/type.Mutex.html#differences-from-the-standard-library-mutex

### CODE REVIEW

**Comment by kw217** [comment]
Is there a need for this? I just read https://github.com/faern/parking_lot/pull/1 and https://github.com/rust-lang/rust/pull/56410 and it seems like `parking_lot` is still a fair way off being considered for the standard library, due to various worries about correctness and developer documentation.

**Comment by jhgg** [comment]
The main motivation is that it's faster under the uncontended case (which is the majority here), and namely, our use of std::Mutex is incorrect anyways as we potentially can panic (although this is super unlikely) from a CFFI function which to my understanding is UB.

**Comment by jhgg** [comment]
anyways - we also run parking_lot in prod without any issue. so aside from a slight increase in compile time this should purely be "faster".

**Review by kw217 — APPROVED** [review]
OK. I see lots of other projects are using parking-lot, and your point about unwrap in CFFI is a very good one.

Code LGTM - thanks for driving this.

**Comment by kw217** [comment]
As with the other ones, this is now out-of-date so needs you to click "update". Best to just do one at a time. I'll try and check regularly during 0900-1700 UTC - is there any overlap with your hours?

**Comment by jhgg** [comment]
Updated.

**Pull request merged**
