### PR TITLE
update cassandra-sys-rs

### PR DESCRIPTION
**Pull request by dimbleby**
see Metaswitch/cassandra-sys-rs#14

### CODE REVIEW

**Comment by dimbleby** [comment]
Not sure why travis thinks this commit is not signed off, but the build will certainly fail anyway until cassandra-sys 0.12 is published.  So let's get that sorted first and then try again here.

**Comment by kw217** [comment]
It is signed off - the error is "error: no matching version `^0.12` found for package `cassandra-cpp-sys` (required by `cassandra-cpp`)". There's no error about signoff, just an echo of the command.

**Comment by kw217** [comment]
LGTM.

**Comment by kw217** [comment]
The README still refers to version 0.10; should be upgraded.

**Comment by kw217** [comment]
README still not updated, and you have conflicts.

**Comment by dimbleby** [comment]
Not sure why github made me resolve the conflicts twice - I suppose I must have pressed a wrong button somewhere...

As for the README: IMO updating that should be part of the release process rather than part of this pull request.  (Also: updating the CHANGELOG to include the release date)

Though actually I'd suggest removing the section that tells you what to put in cargo altogether - it's obvious to anyone with any passing familiarity with what they're doing, and generates the dull chore of keeping it updated.

**Comment by kw217** [comment]
I'm certainly happy with removing the Cargo instructions from the README, thanks.

My only point wrt bumping the version was that if you do it, it should be done everywhere at the same time - README, Cargo, CHANGELOG, VERSION.

**Comment by kw217** [comment]
This is subsumed by #45 . Closing.

**Pull request closed without merging**
