### PR TITLE
cast to *const c_char instead of *const i8 for pointers

### PR DESCRIPTION
**Pull request by aweary**
idk much about unsafe Rust but this fixes the remaining errors I had in https://github.com/Metaswitch/cassandra-rs/issues/116 and I think its right?

### CODE REVIEW

**Comment by aweary** [comment]
cc @kw217

**Review by kw217 — APPROVED** [review]
LGTM - thanks for this!

**Comment by kw217** [comment]
Hi @aweary - I've just spotted that somehow the commit checker didn't run for this commit, and so I didn't notice that you didn't sign your commit per [CONTRIBUTING](https://github.com/Metaswitch/cassandra-rs/blob/master/CONTRIBUTING.md) to acknowledge the Developer Certificate of Origin. Please could you state below "I hereby certify the Developer Certificate of Origin in [CONTRIBUTING](https://github.com/Metaswitch/cassandra-rs/blob/master/CONTRIBUTING.md) with respect to my commit 1206d1506fb7a1df637abe2dac102cfe39e37fb5"? Very sorry about this, but we have to ensure the driver is legally clean so it can continue to be used and distributed freely. Thanks.

**Comment by aweary** [comment]
I hereby certify the Developer Certificate of Origin in CONTRIBUTING with respect to my commit 1206d15

**Comment by kw217** [comment]
Thank you!

**Pull request merged**
